apiVersion: apps/v1
kind: Deployment
metadata:
  name:  plantmicroservice
  labels:
    app: Plant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Plant
  template:
    metadata:
      labels:
        app: Plant
    spec:
      containers:
      - name: rfqcontainerregistry
        image: rfqcontainerregistry.azurecr.io/plantmicros:latest
        imagePullPolicy: Always 
        resources:
        env:
          - name: DefaultConnection
            value: "Server=tcp:rfqserver.database.windows.net,1433;Initial Catalog=PlantMicroService;Persist Security Info=False;User ID=rfq;Password={Supp@1234};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr
---
apiVersion: v1
kind: Service
metadata:
  name: newplant
spec:
  selector:
    app: Plant
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80