apiVersion: apps/v1
kind: Deployment
metadata:
  name:  authmicroservice
  labels:
    app: Auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Auth
  template:
    metadata:
      labels:
        app: Auth
    spec:
      containers:
      - name: rfqcontainerregistry
        image: rfqcontainerregistry.azurecr.io/authmicroservice:latest
        imagePullPolicy: Always 
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr
---
apiVersion: v1
kind: Service
metadata:
  name: newauth
spec:
  selector:
    app: Auth
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80